add STS2 card

diff --git a/scanner/scan_ocp_5g b/scanner/scan_ocp_5g
--- a/scanner/scan_ocp_5g
+++ b/scanner/scan_ocp_5g
@@ -122,11 +122,9 @@ function log_node_resources() {
 	LOGS=$6
 
 	#intel salem channel
-	BASELINE_VENDOR_ID_CVL="0x8086"
-	BASELINE_DEVICE_ID_CVL="0x1593"
-	#if some baseline is reached for subsystem
-	#BASELINE_SUB_ID
-	#BASELINE_SUB_DEV_ID
+	#add vars
+	#sts
+	BASELINE_STS2="3.02"
 
 	echo "#############BIOS######################"
 	if [ -d "/sys/devices/virtual/dmi" ]; then
@@ -161,26 +159,30 @@ function log_node_resources() {
       echo '#########################'$ETH'#############################'
       NIC_FIRMWARE_VERSION_FULL=$(ethtool -i $ETH | grep -i "firmware-version" | cut --complement -d " " -f 1)
 			NIC_FIRMWARE_VERSION=$(ethtool -i $ETH | grep -i "firmware-version" | cut --complement -d " " -f 1 | cut -d " " -f 1)
-      # Check Baseline_E810 CVL
-			if [[ ("$DRIVER" == "ice")  && ("$NIC_FIRMWARE_VERSION" != "$BASELINE_E800") ]]; then
-				echo "ERROR: Baseline CVL "$DRIVER"  NIC_FIRMWARE_VERSION: "$NIC_FIRMWARE_VERSION" BASELINE: "$BASELINE_E800
-				echo "ERROR: Baseline CVL ICE driver with wrong firmware version"
-			fi
-      # Check Baseline_E710 FVL
+      echo "INFO: Driver: "$DRIVER
+			echo "firmware-version: "$NIC_FIRMWARE_VERSION_FULL
+      # Check FVL firmware
 			if  [[ ( "$DRIVER" == "i40e" ) && ("$NIC_FIRMWARE_VERSION" != "$BASELINE_E700") ]]; then
 				echo "ERROR: Baseline FVL: "$DRIVER"  NIC_FIRMWARE_VERSION: "$NIC_FIRMWARE_VERSION" BASELINE: "$BASELINE_E700
 				echo "ERROR: Baseline FVL i40e driver for e710 with wrong firmware version"
 			fi
-      echo "INFO: Driver: "$DRIVER
-			echo "firmware-version: "$NIC_FIRMWARE_VERSION_FULL
+      # Check CVL
 			BUS_PCI=$(ethtool -i $ETH | grep -i "bus-info" | cut -d " " -f 2)
 			echo "$(lspci -vnns $BUS_PCI | head -2)"
-
-			DEVICE_ID=`cat /sys/bus/pci/devices/${BUS_PCI}/device`
-			if [[ ("$DRIVER" == "ice")  && ("$DEVICE_ID" != "$BASELINE_DEVICE_ID_CVL") ]]; then
-				echo "ERROR: BASELINE CVL salem channel device id "$BASELINE_DEVICE_ID_CVL" differs from "$DEVICE_ID
+			if [[ ("$DRIVER" == "ice") ]]; then
+				SUB_DEVICE_ID=`cat /sys/bus/pci/devices/${BUS_PCI}/subsystem_device`
 				#SUB_VENDOR_ID=`cat /sys/bus/pci/devices/${BUS_PCI}`
-				#SUB_DEVICE_ID=`cat /sys/bus/pci/devices/${BUS_PCI}`
+				DEVICE_ID=`cat /sys/bus/pci/devices/${BUS_PCI}/device`
+				# Silicom STS2
+				if [[ ( ("$DEVICE_ID" == "0x1591") && ("0x02d8" == "$SUB_DEVICE_ID") )  && ("$NIC_FIRMWARE_VERSION" != "$BASELINE_STS2") ]]; then
+					echo "ERROR: STS2 Baseline CVL   NIC_FIRMWARE_VERSION: "$NIC_FIRMWARE_VERSION" BASELINE: "$BASELINE_STS2
+					echo "ERROR: STS2 CVL driver with wrong firmware version"
+			  fi
+			  # Intel E810-XXV and E810-C
+				if [[ ( ("$DEVICE_ID" == "0x159b") || ("0x1593" == "$DEVICE_ID") ) && ("$NIC_FIRMWARE_VERSION" != "$BASELINE_E800") ]]; then
+					echo "ERROR: Intel Baseline CVL "$DRIVER"  NIC_FIRMWARE_VERSION: "$NIC_FIRMWARE_VERSION" BASELINE: "$BASELINE_E800
+					echo "ERROR: Intel Baseline CVL with wrong firmware version"
+				fi
 			fi
 
 			echo $ETH' : SRIOV enabled? '
